# Generated by Django 3.2.7 on 2021-10-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Type_Movto',
            fields=[
                ('id', models.IntegerField(max_length=3, primary_key=True, serialize=False, unique=True, verbose_name='Código')),
                ('nome', models.CharField(max_length=30, verbose_name='Descrição')),
                ('natureza', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída')], max_length=1, verbose_name='Natureza')),
                ('sinal', models.CharField(choices=[('+', 'Entrada'), ('-', 'Saída')], max_length=1, verbose_name='Sinal')),
            ],
            options={
                'ordering': ['id', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='Movto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateField(verbose_name='Data da Transação')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Transação')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF do Baneficiário')),
                ('cartao', models.CharField(max_length=12, verbose_name='Cartão Utilizado')),
                ('hora', models.TimeField(verbose_name='Hora da Transação')),
                ('representante_loja', models.CharField(max_length=14, verbose_name='Nome do Representante')),
                ('nome_loja', models.CharField(max_length=19, verbose_name='Nome da Loja')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.type_movto', verbose_name='Tipo de Transação')),
            ],
            options={
                'ordering': ['tipo', 'data', 'cpf', 'nome_loja'],
            },
        ),
    ]
